#!/bin/bash
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "CONFIGS
SCRIPTS
SHELL" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		gedit $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		gedit $1/$selected
	fi
}



if [ "$another" == "SHELL" ] ; then
	selected=$(echo "$HOME/dotfiles/.zshrc
$HOME/dotfiles/.bashrc
$HOME/dotfiles/.tmux.conf
$HOME/dotfiles/.spacevim
$HOME/dotfiles/.alias
$HOME/dotfiles/.Xmodmap
$HOME/.Xdefaults" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
	[[ -z $selected ]] && exit
	gedit $selected

elif [ "$another" == "CONFIGS" ] ; then
	browse /home/bresilla/dotfiles/.config;

elif [ "$another" == "SCRIPTS" ] ; then
	browse /home/.shell;

else
    echo $another
fi
