#!/bin/bash

ag -x "TODO|FIXME|XXX|IDEA|\?\?\?|\!\!\!REF|REQ|HACK|NOTE" \
| ag --flush --passthru --color --color-match="black on_cyan" "TODO" \
| ag --flush --passthru --color --color-match="black on_red" "FIXME" \
| ag --flush --passthru --color --color-match="black on_red" "XXX" \
| ag --flush --passthru --color --color-match="black on_green" "IDEA" \
| ag --flush --passthru --color --color-match="black on_red" "\?\?\?" \
| ag --flush --passthru --color --color-match="black on_green" "\!\!\!" \
| ag --flush --passthru --color --color-match="black on_red" "REF" \
| ag --flush --passthru --color --color-match="black on_yellow" "REQ" \
| ag --flush --passthru --color --color-match="black on_yellow" "HACK" \
| ag --flush --passthru --color --color-match="black on_green" "NOTE" \
| ag -o "(?<=<\!--).*?(?=-->)|(?<=>>).*?(?=<<)" |sort -nr
