#!/bin/bash

today=$(gcalcli --nocolor agenda today 1day)
deadlines=$(gcalcli --nocolor --cal Deadlines agenda today 3w)
gitlog=$(git --git-dir ~/zettel/.git log --name-only --pretty=format:"%h%x09%ar%x09%s" -1)
gitstatus=$(cd ~/zettel && git status|ag [0-9])
gittodo=$(cd ~/zettel && git log -p --since=1.week|ag " \[.?\] ")

deadline=$(
IFS='
'
for line in $deadlines
do
		pattern=" "
		if [[ $line == $pattern* ]]
		then
				line=$(echo $line|awk '$1=$1')
				echo -e "- $line"
		else
				line=$(echo $line|awk '$1=$1')
				date=$(echo $line|cut -d' ' -f -3)
				desc=$(echo $line|cut -d' ' -f 4-)
				datestring=$(echo $line | awk '{print "gdate -d\""$2FS$3"\" +%s"}'|bash)
				now=$(date +%s)
				diff=$(( ($datestring-$now) / (60*60*24) ))
				if [ $diff == 0 ]
				then
						echo -e "\n## Today, on $date\n- $desc"
				else
						diff=$(($diff+1))
						echo -e "\n## In *$diff* Days, on $date\n- $desc"
				fi
		fi
done
)

todoin="$(cd ~/zettel && rg '\[a\]')"

todoout=$(
IFS='
'
for line in $todoin
do
		newline=$(echo $line|sed "s/^20/[[20/g"|sed "s/\.md/\.md]]/g" |sed "s/:/\n/")
		echo -e "$newline\n"
done
)

echo "# Scheduled Today and Tomorrow [[$(date +%Y%m%d).md]] && [[$(gdate --date="tomorrow" +%Y%m%d).md]]"
echo -e "$today" |sed '/^[a-z]/s/^/- /'|tr -s '\n'|sed '/^\ /s/^/   /'

echo -e "\n# Deadlines"
echo "$deadline"

echo -e "\n## Priority todo\n"
echo -e "$todoout"

echo -e "\n# Git Logs\n"

echo -e "\n## Current files\n"
echo "$gitstatus"|sed 's/^	/- /'

echo -e "\n## Recent files\n"
echo "$gitlog"|sed '1 s/^/### /'|sed '1 s/$/\n /'|sed '/^20/s/^/- @/'

echo -e "\n## TODO Changes"
echo -e "\n### Completed\n"
echo -e "$gittodo"|ag "^-"
echo -e "\n### Created\n"
echo -e "$gittodo"|ag "^\+"

