#!/bin/bash

printf "\n\n# Listing Fiction\n\n"
#ls /Volumes/Lagring/fiction |sort -f | sed 's/^/- /' > ~/Videos/fiction/filmer.md
ssh mypi-storage ls /media/pi/seagate/Movies/fiction |sort -f | sed 's/^/- /' > ~/Videos/fiction/filmer.md
cp ~/Videos/fiction/filmer.md ~/notes/md/2020-07-17-2132.r.filmer.md

printf "\n\n# Listing Documentaries\n\n"
#ls /Volumes/Lagring/documentaries|sort -f | sed 's/^/- /' > ~/Videos/documentary/documentaries.md
ssh mypi-storage ls /media/pi/seagate/Movies/documentaries|sort -f | sed 's/^/- /' > ~/Videos/documentary/documentaries.md

printf "\n\n# Listing BJJ\n\n"

# Run the find command remotely and filter only directories
REMOTE_PATH="/media/pi/seagate/bjj/bjj"
DIR_LIST=$(ssh mypi-storage "find \"$REMOTE_PATH\" -type d | sed 's|^$REMOTE_PATH/||'")

# Convert to indented Markdown
echo "$DIR_LIST" | awk -F/ '
{
    depth = NF - 1
    indent = ""
    for (i = 0; i < depth; i++) {
        indent = indent "  "
    }
    print indent "- " $NF
}
' > ~/Videos/bjj/bjj.md
