#!/bin/bash

time="-mtime -$((7 + ${1-0})) -mtime +$((0 + ${1-0}))"


clear

echo  "\n\n# Completed tasks # \n\n"

todo.sh xp $((7 + ${1-0}))

echo  "\n\n# Blog Posts # \n\n"

cd ~/notes/omxi.se/_posts

if [[ -n $(find *.md $time) ]]; then
  ack -i "summary" `find *.md $time`
else
    echo "no blogposts found"
fi

echo  "\n\n# Last weeks notes # \n\n"

cd ~/notes/timenotes
if [[ -n $(find *.txt $time) ]]; then
  find *.txt $time
else
    echo "no notes found"
fi

echo  "\n\n# Last weeks papers # \n\n"

cd ~/Documents/library/papers
if [[ -n $(find *.pdf $time) ]]; then
  find *.pdf $time
else
    echo "no new papers found"
fi

echo "\n\n# Week $(gdate "+%V" -d ''$((1 + ${1-0}))' days ago')"
echo From $(gdate "+%a %b %d" -d ''$((7 + ${1-0}))' days ago') to $(gdate "+%a %b %d" -d ''$((1 + ${1-0}))' days ago')
