#!/bin/bash

# clear 

cd ~/notes/txt

printf "\n\n# Important Tasks\n\n"

ag -Q --color-match "1;33" "* TODO [#A]"

printf "\n\n# Next Tasks\n\n"

ag -Q --color-match "1;34" "* TODO [#B]"

printf "\n\n# Other Tasks\n\n"

ag -A1 --color-match "1;32" "#TODO:"
