#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'pass uid to script, ex 201507030906, or 201407271365'
    exit 0
fi

# Get the original file and functions
file=$1
filetitle=$(ag -g $file)

# Print DOT intro
printf "digraph graphname {\n"
printf "label = \"$filetitle\"\n"

# Incoming links
incoming=$(ag -l $file)
printf "\"$incoming\" -> \"$filetitle\"\n"

# Level 1 outgoing
link=$(ag -o "(?<=§|\[)[0-9]{12}" $file*|sort -n |uniq)
for line in $link
  do
    title=$(ag -g $line)
    printf "\"$filetitle\" -> \"$title\"\n"
    # Level 2 outgoing	
    l2=$(ag -o "(?<=§|\[)[0-9]{12}" $line*|sort -n |uniq)
		for line2 in $l2
				do
						title2=$(ag -g $line2)
						printf "\"$title\" -> \"$title2\"\n"
						# Level 3 outgoing						
						l3=$(ag -o "(?<=§|\[)[0-9]{12}" $line2*|sort -n |uniq)
								for line3 in $l3
										do
												title3=$(ag -g $line3)
												printf "\"$title2\" -> \"$title3\"\n"
										done
				done
  done
# The End
printf "}"
