#! /bin/bash

FILE="$TODO_FILE"
## If the file starts with a "/" use absolute path. Otherwise,
## try to find it in either $TODO_DIR or using a relative path
if [ "${1:0:1}" == / ]; then
   ## Absolute path
   src="$FILE"
elif [ -f "$TODO_DIR/$FILE" ]; then
   ## Path relative to todo.sh directory
   src="$TODO_DIR/$FILE"
elif [ -f "$FILE" ]; then
   ## Path relative to current working directory
   src="$FILE"
elif [ -f "$TODO_DIR/${FILE}.txt" ]; then
   ## Path relative to todo.sh directory, missing file extension
   src="$TODO_DIR/${FILE}.txt"
else
   die "TODO: File $FILE does not exist."
fi

ORDERED=`env LC_COLLATE=C sort -f "$src"`

echo "$ORDERED" > "$src"

echo "$TODO_FILE ordered."
