#! /bin/sh

sxhkd &

bspc monitor -d web term chat code music

bspc config border_width         0 
bspc config window_gap           37 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc desktop ^1 -l tiled

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Google-chrome desktop=^1
bspc rule -a Spotify desktop=^5
bspc rule -a Lmms desktop=^5
bspc rule -a mplayer2 state=floating
bspc rule -a Eog state=floating
#bspc rule -a Nautilus state=floating
bspc rule -a File-roller state=floating
bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr
 
feh --randomize --bg-fill ~/Dropbox/wallpapers
#gnome-wallpaper-changer &
compton --config ~/.config/compton.conf -b
polybar top &
nm-applet &
autokey &
dropbox start &
kdeconnect-indicator &
dunst -conf ~/.config/dunst/config &
redshift &

xrdb -merge ~/.Xresources
sleep 2;xmodmap /home/svartfax/.Xmodmap
xcape


#panel &

